// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAySR7woiHtV2pEudd33u__olVLwwSlvVc',
    appId: '1:1086733183084:web:b9500c8ce48fa55ae4d049',
    messagingSenderId: '1086733183084',
    projectId: 'el-puestito-kds',
    authDomain: 'el-puestito-kds.firebaseapp.com',
    storageBucket: 'el-puestito-kds.firebasestorage.app',
    measurementId: 'G-V17LRF30Y7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_-sayVPpRH1PjKzKgq2E7txjZHmPAgVE',
    appId: '1:1086733183084:android:4cf667f7f92e8f29e4d049',
    messagingSenderId: '1086733183084',
    projectId: 'el-puestito-kds',
    storageBucket: 'el-puestito-kds.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlNNsfdB394xJW7aBw2ATUAvBScqAnLbM',
    appId: '1:1086733183084:ios:21fbc69e4e1077a4e4d049',
    messagingSenderId: '1086733183084',
    projectId: 'el-puestito-kds',
    storageBucket: 'el-puestito-kds.firebasestorage.app',
    iosBundleId: 'com.example.posWaiterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlNNsfdB394xJW7aBw2ATUAvBScqAnLbM',
    appId: '1:1086733183084:ios:21fbc69e4e1077a4e4d049',
    messagingSenderId: '1086733183084',
    projectId: 'el-puestito-kds',
    storageBucket: 'el-puestito-kds.firebasestorage.app',
    iosBundleId: 'com.example.posWaiterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAySR7woiHtV2pEudd33u__olVLwwSlvVc',
    appId: '1:1086733183084:web:1bca1f02b8b51aefe4d049',
    messagingSenderId: '1086733183084',
    projectId: 'el-puestito-kds',
    authDomain: 'el-puestito-kds.firebaseapp.com',
    storageBucket: 'el-puestito-kds.firebasestorage.app',
    measurementId: 'G-B62M6P96H1',
  );
}
